### ISSUE TITLE
Refine w60x port to allow standard use within Thonny

### ISSUE THREAD

**Issue by LexxM3** [robert-hh/micropython#15]
This is a request specific to the w60x port and branch.  Support for modern Micropython has now made it possible to use Thonny and it now basically works as expected (filesystem access without the need for the FTP server, ability to run editor code without transferring files, etc.) , but a few of the otherwise-very-convenient w60x port refinements seem to interfere with routine Thonny REPL operations.  

Specifically, for some reason, every linefeed in Thonny REPL window generates a `upysh` `ls` command directory list output!  There might be other issues, but this one stands out right away.

Perhaps there is a way to retain the `upysh`, `pye`, and `_boot.py` conveniences in these images while still allowing full Thonny operations?

**Comment by robert-hh** [comment]
I can check. The upysh and pye modules are just my personal preferences. They do not have to be in a standard firmware. I avoid using Thonny. I do not like the "magic" it does under the hood, causing "surprises". But I see that many people use it as convenient IDE, as long as it works. what comes up from upysh in the splash message, since thonny seems to force a reboot at every line feed. The splash message can be dropped. That's easy. And I have to check what Thonny does. If only _boot.py is imported, then I can remove importing upysh and pye there and leave it to a user's main.py. I'm wondering why there is a upysh directory list output. 
Maybe Thonny requests it intentionally for a directory listing but just misses to catch the output properly.

**Comment by robert-hh** [comment]
Looking at what thonny does, it's a thonny "magic". Thonny lists the values of all local variable. Listing 'ls' causes the ls function to be executed. So the only way to avoid it is not to import upysh by default.

Edit: The repo is updated. upysh is not started on boot.

**Comment by LexxM3** [comment]
Excellent.  I can confirm that Thonny is behaving quite a bit better and is now very usable for bring-up and general development on W600.  Tested the sole image so far with that update: [wm_w600_lfs.fls](https://github.com/robert-hh/Shared-Stuff/blob/master/wm_w600_lfs.fls).

Thonny is not perfect, but one solid advantage to Thonny for beginners (or even experts turning on a new board for the first time) is that it gives you access to the filesystem without additional configuration (without Thonny, one has to manually configure serial, wifi, and ftpserver access which IS workable, but is relatively involved).  With stock 1.10 Micropython images on the W600, Thonny was not able to access the filesystem.  With 1.19 it does and this is partially why I am so excited about your work here -- it makes bring-up _**drastically**_ easier than with the stock shipped image and that, in turn, makes W600 _**drastically**_ more accessible to more people whom would have otherwise given up on the W600 in its stock shipped form.

And that in turn will increase W600's popularity.  Personally, I love the cost vs. capability level of the W600 and, frankly, want it to become popular (as long as the cost/capabilities remains the same or improves -- W600-PICO at $4 isn't worth the trouble relative to the alternatives, but it is at $1-$1.50).

**Comment by robert-hh** [comment]
I did not update the other image variants, and I consider dropping the FAT variants. They are only needed if you want to use a SD card with the W600. Due to the implementation of the ftp server, it cannot handle both file systems at the same time. That's why there are two FS variants. Then still a variant with and w/o threading exist. Threading uses more RAM, so it is not really a good option. Better use asyncio, which is supported in all variants.

**Comment by robert-hh** [comment]
A agree to your position about the W600. It is the better alternative to the ESP8266, having WiFi as well, but more memory and more interfaces at an unbeatable price. Alternatives are the SEEED XIAO boards. They are small, and at a price tag of about $5 you have an ESP32C3, SAMD21 and RP2040 variant. And Seeed gives a really good support for their devices.

**Comment by LexxM3** [comment]
Closing the issue.  Summary notes: Thonny operation has been tested over multiple builds and multiple days.  The only thing that had originally prevented clean Thonny operation was the `from upysh import *` style of upysh use and since that is no longer done in _boot.py by default, Thonny works great out of the box.
